name: Maven build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 16
      uses: actions/setup-java@v2.1.0
      with:
        java-version: '16'
        distribution: 'adopt'
        java-package: jdk
        architecture: x64
    - name: Build with Maven
      run: mvn package --file pom.xml
