name: SonarCloud Scanner

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:

    name: SonarCloud Scanner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up Java 16
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '16'
          distribution: 'adopt'
          java-package: jdk
          architecture: x64
      - name: SonarCloud analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
